coverage:
  precision: 2
  round: down
  range: "70...90"
  status:
    project:
      default:
        target: auto    # the required coverage value
        threshold: 0.2%  # the leniency in hitting the target
