openapi: 3.0.3
info:
  title: Hello World
  description: This is a sample Hello World extension.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-SNAPSHOT
tags:
  - name: hello
    description: Worldly Greetings
paths:
  /hello:
    get:
      tags:
        - hello
      summary: Greet the world
      description: Traditional greeting
      responses:
        '200':
          description: Successful operation
          content:
            text/plain; charset=utf-8:
              examples:
                Default Response:
                  value: Hello, World!
        '400':
          description: Syntax Error in URI
        '404':
          description: Improper REST action configuration
    post:
      tags:
        - hello
      summary: Adds a descriptive world adjective to a list
      description: >-
        Adds an adjective to a list from which a random element will be
        prepended to the world name
      operationId: ''
      requestBody:
        description: An adjective in plain text or JSON
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                adjective:
                  type: string
                  example: wonderful
          text/plain:
            schema:
              type: string
              example: wonderful
      responses:
        '200':
          description: Successful operation
        '400':
          description: Syntax Error in request
        '404':
          description: Improper REST action configuration
        '406':
          description: Content format not text or JSON
    delete:
      tags:
        - hello
      summary: Removes an adjective from the list
      description: >-
        Removes an adjective from the list from which a random element
        will be prepended to the world name
      operationId: ''
      responses:
        '200':
          description: Successful operation
        '304':
          description: Adjective not in the list, no action taken
        '400':
          description: Syntax Error in request
        '404':
          description: Improper REST action configuration
        '406':
          description: Content format not text or JSON
  /hello/{name}:
    put:
      tags:
        - hello
      summary: Rename the world
      description: Update the world to a custom name
      parameters:
        - name: name
          in: path
          description: A new name for the world
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            text/plain; charset=utf-8:
              examples:
                Default Response:
                  value: Updated the world's name to OpenSearch
        '400':
          description: Syntax Error in URI
        '404':
          description: Improper REST action configuration
  /goodbye:
    delete:
      tags:
        - hello
      summary: Restores the world to default
      description: >-
        Removes all adjectives and the custom world name
      operationId: ''
      responses:
        '200':
          description: Successful operation
