name: Gradle Build
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # needed for git diff to find main branch
          fetch-depth: "0"
      - name: Spotless Check
        run: ./gradlew spotlessCheck
  check:
    needs: spotless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: opensearch-project/OpenSearch
          ref: feature/extensions
      - name: Publish to Maven Local
        run: |
          ./gradlew publishToMavenLocal
      - uses: actions/checkout@v3
        with:
          # needed for git diff to find main branch
          fetch-depth: "0"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Run Gradle Check
        run: |
          ./gradlew check
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
