name: Gradle Build
on:
  push:
    branches-ignore:
      - 'backport/**'
      - 'whitesource-remediate/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spotless Check
        run: ./gradlew spotlessCheck
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Javadoc CheckStyle
        run: ./gradlew checkstyleMain
      - name: Javadoc Check
        run: ./gradlew javadoc
  check:
    needs: [spotless, javadoc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Run Gradle Check
        run: |
          ./gradlew check
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
  publish:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish to Maven Local
      run: ./gradlew publishToMavenLocal
